### ISSUE TITLE
Benchmark the the loading of keys from yaml files

### ISSUE THREAD

**Issue by arash009** [PegaSysEng/eth2signer#30]
Some benchmarking of what performance is like when reading from yaml files. Need to consider what the limits are (~10s, ~100s, ~1000s)

Can run this locally first and see if performance is sufficient, can then check on cloud providers.

**Comment by jframe** [comment]
Loading of keys does affect how long eth2signer takes to startup.

I measured the startup time was measured by generating n BLS keystore files using scrypt and measuring the time taken for the health endpoint to be active.

BLS keystore using scrypt with dklen=32, n=262144, p=1, r=8

* 100 keys without optimisation took 84640
* 100 keys using java parallelstream took 22864
* 1000 keys without optimisation took 820411
* 1000 keys using java parallelstream took 210449

For 210 ms/key on average (with parallelstream optimization)

The parallelstream optimisation changes the key loading to use the Java parallelStream no other optimisation is being done.

Since the parallelstream optimisation is a simple change to make has large improvement on performance I will make that change in PR for Eth2Signer.
